CREATE TABLE email_verification_token
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    token       VARCHAR(255),
    register_id BIGINT,
    expiry_date TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_oversimplification PRIMARY KEY (id)
);

CREATE TABLE password_reset_token
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    token       VARCHAR(255),
    register_id BIGINT,
    expiry_date TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_passwordresettoken PRIMARY KEY (id)
);

ALTER TABLE admin_activity
    ADD email VARCHAR(255);

ALTER TABLE register
    ADD google_id VARCHAR(255);

ALTER TABLE register
    ADD provider VARCHAR(255);

ALTER TABLE register
    ADD provider_id VARCHAR(255);

ALTER TABLE register
    ALTER COLUMN provider SET NOT NULL;

ALTER TABLE personal_information
    ADD CONSTRAINT uc_personal_information_application UNIQUE (application_id);

ALTER TABLE register
    ADD CONSTRAINT uc_register_googled UNIQUE (google_id);

ALTER TABLE register
    ADD CONSTRAINT uc_register_providerid UNIQUE (provider_id);

ALTER TABLE users
    ADD CONSTRAINT uc_users_register UNIQUE (register_id);

ALTER TABLE email_verification_token
    ADD CONSTRAINT FK_OVERSIMPLIFICATION_ON_REGISTER FOREIGN KEY (register_id) REFERENCES register (id);

ALTER TABLE password_reset_token
    ADD CONSTRAINT FK_PASSWORDRESETTOKEN_ON_REGISTER FOREIGN KEY (register_id) REFERENCES register (id);

ALTER TABLE admin_users
DROP
COLUMN created_at;

ALTER TABLE admin_users
DROP
COLUMN updated_at;

ALTER TABLE admin_users
DROP
COLUMN id;

ALTER TABLE admin_users
DROP
COLUMN role;

ALTER TABLE disability_information
DROP
COLUMN created_at;

ALTER TABLE disability_information
DROP
COLUMN updated_at;

ALTER TABLE disability_information
DROP
COLUMN id;

ALTER TABLE disability_information
DROP
COLUMN personal_information_id;

ALTER TABLE documents
DROP
COLUMN created_at;

ALTER TABLE documents
DROP
COLUMN updated_at;

ALTER TABLE documents
DROP
COLUMN id;

ALTER TABLE documents
DROP
COLUMN personal_information_id;

ALTER TABLE education_occupation
DROP
COLUMN created_at;

ALTER TABLE education_occupation
DROP
COLUMN updated_at;

ALTER TABLE education_occupation
DROP
COLUMN id;

ALTER TABLE education_occupation
DROP
COLUMN personal_information_id;

ALTER TABLE emergency_contacts
DROP
COLUMN created_at;

ALTER TABLE emergency_contacts
DROP
COLUMN updated_at;

ALTER TABLE emergency_contacts
DROP
COLUMN id;

ALTER TABLE emergency_contacts
DROP
COLUMN personal_information_id;

ALTER TABLE motivation_answers
DROP
COLUMN created_at;

ALTER TABLE motivation_answers
DROP
COLUMN updated_at;

ALTER TABLE motivation_answers
DROP
COLUMN id;

ALTER TABLE motivation_answers
DROP
COLUMN personal_information_id;

ALTER TABLE vulnerability_information
DROP
COLUMN created_at;

ALTER TABLE vulnerability_information
DROP
COLUMN updated_at;

ALTER TABLE vulnerability_information
DROP
COLUMN id;

ALTER TABLE vulnerability_information
DROP
COLUMN personal_information_id;

ALTER TABLE admin_activity
ALTER
COLUMN action TYPE VARCHAR(255) USING (action::VARCHAR(255));

ALTER TABLE admin_activity
DROP
COLUMN admin_id;

ALTER TABLE admin_activity
DROP
COLUMN application_id;

ALTER TABLE admin_activity
DROP
COLUMN id;

ALTER TABLE admin_activity
    ADD admin_id BIGINT;

ALTER TABLE admin_activity
    ADD CONSTRAINT FK_ADMIN_ACTIVITY_ON_ADMIN FOREIGN KEY (admin_id) REFERENCES admin_users (id);

ALTER TABLE admin_activity
    ALTER COLUMN admin_id DROP NOT NULL;

ALTER TABLE admin_activity
    ADD application_id BIGINT;

ALTER TABLE admin_activity
    ADD CONSTRAINT FK_ADMIN_ACTIVITY_ON_APPLICATION FOREIGN KEY (application_id) REFERENCES applications (id);

ALTER TABLE personal_information
DROP
COLUMN application_id;

ALTER TABLE personal_information
DROP
COLUMN id;

ALTER TABLE personal_information
    ADD application_id BIGINT;

ALTER TABLE personal_information
    ADD CONSTRAINT uc_personal_information_application UNIQUE (application_id);

ALTER TABLE personal_information
    ADD CONSTRAINT FK_PERSONAL_INFORMATION_ON_APPLICATION FOREIGN KEY (application_id) REFERENCES applications (id);

ALTER TABLE personal_information
    ALTER COLUMN application_id DROP NOT NULL;

ALTER TABLE applications
DROP
COLUMN cohort_id;

ALTER TABLE applications
DROP
COLUMN id;

ALTER TABLE applications
DROP
COLUMN status;

ALTER TABLE applications
DROP
COLUMN user_id;

ALTER TABLE applications
    ADD cohort_id BIGINT;

ALTER TABLE applications
    ADD CONSTRAINT uc_09ffa7296a548ea6b56f0cae4 UNIQUE (cohort_id);

ALTER TABLE applications
    ADD CONSTRAINT FK_APPLICATIONS_ON_COHORT FOREIGN KEY (cohort_id) REFERENCES cohorts (id);

ALTER TABLE applications
    ALTER COLUMN cohort_id DROP NOT NULL;

ALTER TABLE cohort_requirements
DROP
COLUMN cohort_id;

ALTER TABLE cohort_requirements
DROP
COLUMN id;

ALTER TABLE cohort_requirements
    ADD cohort_id BIGINT;

ALTER TABLE cohort_requirements
    ADD CONSTRAINT FK_COHORT_REQUIREMENTS_ON_COHORT FOREIGN KEY (cohort_id) REFERENCES cohorts (id);

ALTER TABLE cohort_requirements
    ALTER COLUMN cohort_id DROP NOT NULL;

ALTER TABLE cohort_requirements
ALTER
COLUMN description TYPE VARCHAR(255) USING (description::VARCHAR(255));

ALTER TABLE admin_users
    ALTER COLUMN email DROP NOT NULL;

ALTER TABLE admin_activity
    ADD id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY;

ALTER TABLE admin_users
    ADD id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY;

ALTER TABLE applications
    ADD id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY;

ALTER TABLE applications
    ADD CONSTRAINT uc_09ffa7296a548ea6b56f0cae4 UNIQUE (id);

ALTER TABLE cohort_requirements
    ADD id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY;

ALTER TABLE cohorts
DROP
COLUMN id;

ALTER TABLE cohorts
    ADD id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY;

ALTER TABLE disability_information
    ADD id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY;

ALTER TABLE documents
    ADD id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY;

ALTER TABLE education_occupation
    ADD id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY;

ALTER TABLE emergency_contacts
    ADD id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY;

ALTER TABLE motivation_answers
    ADD id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY;

ALTER TABLE personal_information
    ADD id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY;

ALTER TABLE personal_information
    ADD CONSTRAINT uc_personal_information_application UNIQUE (id);

ALTER TABLE users
DROP
COLUMN id;

ALTER TABLE users
DROP
COLUMN register_id;

ALTER TABLE users
    ADD id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY;

ALTER TABLE users
    ADD CONSTRAINT uc_users_register UNIQUE (id);

ALTER TABLE vulnerability_information
    ADD id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY;

ALTER TABLE applications
    ALTER COLUMN is_system_rejected SET NOT NULL;

ALTER TABLE register
    ALTER COLUMN is_verified SET NOT NULL;

ALTER TABLE personal_information
ALTER
COLUMN marital_status TYPE VARCHAR(255) USING (marital_status::VARCHAR(255));

ALTER TABLE admin_users
    ALTER COLUMN password DROP NOT NULL;

ALTER TABLE register
    ALTER COLUMN password DROP NOT NULL;

ALTER TABLE disability_information
    ADD personal_information_id BIGINT;

ALTER TABLE disability_information
    ADD CONSTRAINT FK_DISABILITY_INFORMATION_ON_PERSONALIZATION FOREIGN KEY (personal_information_id) REFERENCES personal_information (id);

ALTER TABLE disability_information
    ALTER COLUMN personal_information_id DROP NOT NULL;

ALTER TABLE documents
    ADD personal_information_id BIGINT;

ALTER TABLE documents
    ADD CONSTRAINT FK_DOCUMENTS_ON_PERSONALIZATION FOREIGN KEY (personal_information_id) REFERENCES personal_information (id);

ALTER TABLE documents
    ALTER COLUMN personal_information_id DROP NOT NULL;

ALTER TABLE education_occupation
    ADD personal_information_id BIGINT;

ALTER TABLE education_occupation
    ADD CONSTRAINT FK_EDUCATION_OCCUPATION_ON_PERSONALIZATION FOREIGN KEY (personal_information_id) REFERENCES personal_information (id);

ALTER TABLE education_occupation
    ALTER COLUMN personal_information_id DROP NOT NULL;

ALTER TABLE emergency_contacts
    ADD personal_information_id BIGINT;

ALTER TABLE emergency_contacts
    ADD CONSTRAINT FK_EMERGENCY_CONTACTS_ON_PERSONALIZATION FOREIGN KEY (personal_information_id) REFERENCES personal_information (id);

ALTER TABLE emergency_contacts
    ALTER COLUMN personal_information_id DROP NOT NULL;

ALTER TABLE motivation_answers
    ADD personal_information_id BIGINT;

ALTER TABLE motivation_answers
    ADD CONSTRAINT FK_MOTIVATION_ANSWERS_ON_PERSONALINFORMATION FOREIGN KEY (personal_information_id) REFERENCES personal_information (id);

ALTER TABLE motivation_answers
    ALTER COLUMN personal_information_id DROP NOT NULL;

ALTER TABLE vulnerability_information
    ADD personal_information_id BIGINT;

ALTER TABLE vulnerability_information
    ADD CONSTRAINT FK_VULNERABILITY_INFORMATION_ON_PERSONALIZATION FOREIGN KEY (personal_information_id) REFERENCES personal_information (id);

ALTER TABLE vulnerability_information
    ALTER COLUMN personal_information_id DROP NOT NULL;

ALTER TABLE emergency_contacts
ALTER
COLUMN phone TYPE VARCHAR(255) USING (phone::VARCHAR(255));

ALTER TABLE personal_information
ALTER
COLUMN phone TYPE VARCHAR(255) USING (phone::VARCHAR(255));

ALTER TABLE users
    ADD register_id BIGINT NOT NULL;

ALTER TABLE users
    ADD CONSTRAINT uc_users_register UNIQUE (register_id);

ALTER TABLE users
    ADD CONSTRAINT FK_USERS_ON_REGISTER FOREIGN KEY (register_id) REFERENCES register (id);

ALTER TABLE admin_users
    ADD role VARCHAR(255);

ALTER TABLE admin_users
    ALTER COLUMN role DROP NOT NULL;

ALTER TABLE register
    ALTER COLUMN role DROP NOT NULL;

ALTER TABLE personal_information
ALTER
COLUMN social_links TYPE VARCHAR(255) USING (social_links::VARCHAR(255));

ALTER TABLE applications
    ADD status VARCHAR(255);

ALTER TABLE applications
    ADD user_id BIGINT;

ALTER TABLE applications
    ADD CONSTRAINT uc_09ffa7296a548ea6b56f0cae4 UNIQUE (user_id);

ALTER TABLE applications
    ADD CONSTRAINT FK_APPLICATIONS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE applications
    ALTER COLUMN user_id DROP NOT NULL;

ALTER TABLE register
    ALTER COLUMN username DROP NOT NULL;

ALTER TABLE admin_activity
    ADD CONSTRAINT pk_admin_activity PRIMARY KEY (id);

ALTER TABLE admin_users
    ADD CONSTRAINT pk_admin_users PRIMARY KEY (id);

ALTER TABLE applications
    ADD CONSTRAINT pk_applications PRIMARY KEY (id);

ALTER TABLE cohort_requirements
    ADD CONSTRAINT pk_cohort_requirements PRIMARY KEY (id);

ALTER TABLE cohorts
    ADD CONSTRAINT pk_cohorts PRIMARY KEY (id);

ALTER TABLE disability_information
    ADD CONSTRAINT pk_disability_information PRIMARY KEY (id);

ALTER TABLE documents
    ADD CONSTRAINT pk_documents PRIMARY KEY (id);

ALTER TABLE education_occupation
    ADD CONSTRAINT pk_education_occupation PRIMARY KEY (id);

ALTER TABLE emergency_contacts
    ADD CONSTRAINT pk_emergency_contacts PRIMARY KEY (id);

ALTER TABLE motivation_answers
    ADD CONSTRAINT pk_motivation_answers PRIMARY KEY (id);

ALTER TABLE personal_information
    ADD CONSTRAINT pk_personal_information PRIMARY KEY (id);

ALTER TABLE users
    ADD CONSTRAINT pk_users PRIMARY KEY (id);

ALTER TABLE vulnerability_information
    ADD CONSTRAINT pk_vulnerability_information PRIMARY KEY (id);